dataset: "salicon" # "salicon" | "dhf1k" 
n_epochs: 10
learning_rate: 1e-3
weight_decay: 1e-6
batch_size: 1
accumulation_steps: 1
evaluation_steps: 10
splits: [0.9, 0.05, 0.05]
save_model: True
use_scaler: True
with_transforms: True

hidden_channels: 64
neighbor_radius: 1
n_iterations: 3
with_graph_processing: True
freeze_encoder: True
dropout_rate: 0.0
with_graph_edge_features: True
with_graph_positional_embeddings: True
with_graph_directional_kernels: True
with_depth_information: True