dataset: "salicon" # "salicon" | "dhf1k" 
n_epochs: 5
learning_rate: 1e-3
weight_decay: 1e-6
batch_size: 32
accumulation_steps: 1
evaluation_steps: 40
splits: [0.6, 0.3, 0.1]
save_model: True
use_scaler: True
with_transforms: True

hidden_channels: 64
neighbor_radius: 1
n_iterations: 3
with_graph_processing: True
freeze_encoder: True
with_depth_information: False
dropout_rate: 0.0