n_epochs: 5
learning_rate: 1e-3
weight_decay: 1e-6
batch_size: 64
accumulation_steps: 1
evaluation_steps: 20
splits: [0.7, 0.15, 0.15]
save_model: True
use_scaler: True
with_transforms: True

hidden_channels: 64
output_channels: 5
with_absolute_positional_embeddings: True
with_relative_positional_embeddings: True
n_heads: 1
neighbor_radius: 1
n_iterations: 5
with_graph_processing: True
freeze_encoder: True
with_depth_information: True
fusion_level: 4