dataset: "dhf1k" # "salicon" | "dhf1k" 
n_epochs: 10
learning_rate: 1e-5
weight_decay: 1e-3
batch_size: 1
evaluation_steps: 2048
splits: [0.5, 0.25, 0.25]
use_challenge_split: False
save_model: True
with_transforms: True

image_n_levels: 5
freeze_encoder: False
freeze_temporal_pipeline: False
hidden_channels: 32 # TODO: change this variable
neighbor_radius: 1
n_iterations: 5
image_hidden_channels_list: [8, 16, 16, 32]
depth_hidden_channels_list: [8, 16]
output_type: "temporal"
dropout_rate: 0.2
with_graph_processing: True
with_graph_edge_features: True
with_graph_positional_embeddings: True
with_graph_directional_kernels: True
with_depth_information: True
with_checkpoint: False