dataset: "salicon" # "salicon" | "dhf1k" 
n_epochs: 10
learning_rate: 1e-3
weight_decay: 1e-6
batch_size: 4
evaluation_steps: 64
splits: [0.7, 0.15, 0.15]
use_challenge_split: True
save_model: True
with_transforms: True

freeze_encoder: True
freeze_temporal_pipeline: True
hidden_channels_list: [96, 270, 256, 512]
output_type: "global"
dropout_rate: 0.1
with_checkpoint: True