dataset: "viewout" # "salicon" | "dhf1k" | "viewout"
n_epochs: 10
learning_rate: 1e-4
weight_decay: 1e-6
batch_size: 1
evaluation_steps: 400
splits: [0.5, 0.25, 0.25]
save_model: True
with_transforms: True

freeze_encoder: False
hidden_channels_list: [96, 270, 256, 512]
dropout_rate: 0.0
with_checkpoint: False