n_epochs: 5
learning_rate: 1e-3
weight_decay: 1e-6
batch_size: 32
accumulation_steps: 1
evaluation_steps: 40
splits: [0.7, 0.2, 0.1]
save_model: True
use_scaler: True
with_transforms: True

freeze_encoder: True
hidden_channels_list: [96, 270, 256, 512]