n_epochs: 5
learning_rate: 1e-3
weight_decay: 1e-6
batch_size: 128
accumulation_steps: 1
evaluation_steps: 10
splits: [0.6, 0.3, 0.1]
save_model: True
use_scaler: True
with_transforms: True

decoder_output_channels: 1
freeze_encoder: True