n_epochs: 5
learning_rate: 1e-3
weight_decay: 1e-6
batch_size: 32
accumulation_steps: 1
evaluation_steps: 40
splits: [0.7, 0.15, 0.15]
save_model: True
use_scaler: True
with_transforms: True

input_channels: 3
output_channels: 1
input_shape: [5, 331, 331]
hidden_channels_list: [64, 128, 256, 512]
kernel_sizes: [5, 3, 3, 3]
use_max_poolings: [False, True, False, False]
saliency_out_channels: 64
attention_out_channels: 16
with_depth_information: True