import sys
from pathlib import Path

GLOBAL_DIR = Path(__file__).parent / ".."
sys.path.append(str(GLOBAL_DIR))

import torch

DATA_PATH = str(GLOBAL_DIR / "data")
GAZE_PATH = f"{DATA_PATH}/gaze"
SETS_PATH = f"{DATA_PATH}/sets"
SAMPLES_PATH = f"{DATA_PATH}/samples"
GROUND_TRUTHS_PATH = f"{DATA_PATH}/ground_truths"
MODELS_PATH = f"{DATA_PATH}/models"

FIXATION_DATA_PATH = f"{GAZE_PATH}/fixation_data.csv"

DEFAULT_DATASET_VIDEO_START_SEC = 5
DEFAULT_DATASET_VIDEO_STOP_SEC = 60
DEFAULT_DATASET_SAMPLE_FPS = 5
DEFAULT_DATASET_SAMPLE_LENGTH = 5
DEFAULT_DATASET_GROUND_TRUTH_KDE_BANDWIDTH = 0.4

FPS = 25

RAW_GAZE_FRAME_WIDTH = 6144
RAW_GAZE_FRAME_HEIGHT = 3072
IMAGE_WIDTH = 2396
IMAGE_HEIGHT = 860

SEED = 0
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"